name: firstWorkflow 

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: print a welcome message
        run: echo "Wellcome"     

      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: list repository
        run: ls -la
